import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#0F0F0F" },
  scroll: { flex: 1 },
  content: { paddingBottom: 24 },
  headerWrap: { paddingHorizontal: 16, paddingTop: 18 },
  headerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  profileLink: { flexDirection: "row", alignItems: "center" },
  profileIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#1F1F1F",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  profileName: { color: "#FFFFFF", fontSize: 18, fontWeight: "600" },
  qrWrap: { width: 28, height: 28, alignItems: "center", justifyContent: "center" },
  categoriesWrap: { paddingHorizontal: 16, marginTop: 18 },
  categoriesRow: { flexDirection: "row", justifyContent: "space-between" },
  category: { alignItems: "center", width: "25%" },
  categoryIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#1F1F1F",
    alignItems: "center",
    justifyContent: "center",
  },
  categoryLabel: { color: "#CECECE", marginTop: 6, fontSize: 12 },
  cardsWrap: { paddingHorizontal: 16, marginTop: 18 },
  cardsRow: { flexDirection: "row", alignItems: "center" },
  cardPrimary: {
    flex: 1,
    backgroundColor: "#FF6A00",
    borderRadius: 16,
    height: 120,
    padding: 16,
    marginRight: 12,
  },
  cardPrimaryTitle: { color: "#FFFFFF", fontSize: 20, fontWeight: "700" },
  cardPrimarySub: { color: "#FFFFFF", opacity: 0.8, marginTop: 6 },
  cardSecondary: {
    flex: 1,
    backgroundColor: "#D0D0D0",
    borderRadius: 16,
    height: 120,
    padding: 16,
  },
  cardSecondaryTitle: { color: "#1A1A1A", fontSize: 20, fontWeight: "700" },
  cardSecondarySub: { color: "#1A1A1A", opacity: 0.8, marginTop: 6 },
  addCard: {
    width: 44,
    height: 120,
    borderRadius: 16,
    backgroundColor: "#1F1F1F",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 12,
  },
  addCardPlus: { color: "#FFFFFF", fontSize: 22 },
  expensesWrap: { paddingHorizontal: 16, marginTop: 22 },
  expensesRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  expensesTitle: { color: "#FFFFFF", fontSize: 22, fontWeight: "700" },
  expensesTitleHighlight: { color: "#FF6A00" },
  expensesSum: { color: "#CECECE" },
  expensesBars: { flexDirection: "row", marginTop: 12 },
  bar: { flex: 1, height: 8, borderRadius: 4 },
  barSpacer: { marginRight: 8 },
});
